### ISSUE TITLE
Round robin 

### ISSUE THREAD

**Issue by viniciusfcf** [feralc/rinha-de-backend-2024#1]
Para rinha devemos usar round robin no LB

**Comment by feralc** [comment]
> Para rinha devemos usar round robin no LB

Fala @viniciusfcf! Obrigado pelo feedback! :)

Como o principal objetivo da rinha é de compartilharmos conhecimento, e nesse caso do load balancer com round robin, eu não vi uma nota do tipo "– isso é imprescindível!" como foi deixada para o caso do cadastro dos clientes, e como nos foi dada a liberdade de implementar nosso proprio load balancer, achei que seria interessante usar um simples algoritimo para consistent hashing que casaria muito bem com a solução do actor model. 

Mas comprendo! E mesmo que eu não chegue a vencer, foi legal construir essa solução, onde eu criei uma implementação simples, mas própria do actor model + loadbalancer com backends gRPC + event sourcing "like" + snapshoting  etc etc. Foram muitos aprendizados e reforços de conhecimentos que eu já possuia. Eu queria construir uma solução diferente da mais direta que seria deixar o banco de dados fazer o controle da concorrência, uma vez que ele já é um componente comum entre os nodes e "naturalmente distribuido". Acredito que são conhecimentos que os mais iniciantes podem se beneficiar ou no mínimo despertar a curiosidade, e de igual modo os mais experientes como você podem contribuir, como o caso agora :) 

Para usar um algoritimo de round robin, e se eu ainda continuasse optando pelo actor model, eu teria que criar uma versão distribuida do actor system, onde a "mail box" do actor fosse implementada em cima de algum sistema de mensageria, ou uma outra alternativa como comunicação inter-node pra rotear a mensagem pro node correto, mas tudo isso me pareceu muito overhead pros objetivos da rinha, ainda mais do que adiantaria um load balancer round robin, se por baixo dos panos eu teria que redistribuir todo o tráfego? (claro, digo isso me baseando na solução de actors). Mas eu amo desafios! Quem sabe se eu conseguir um tempo eu implemente uma segunda versão dessa forma ou tente utilizar algum framework ou lib.

**Comment by viniciusfcf** [comment]
Entendo. Mas nas regras está bem claro sim. 

Eu também não devo ganhar, nem entrei pra ganhar. Mas como vc submeteu para partiricar, seria interessante seguir essas regras. 

Se fez para aprender, e eu acho q foi isso, massa. Publica o resultado no Twitter normal sem submeter talvez

![Screenshot_20240219_073401_GitHub.jpg](https://github.com/feralc/rinha-de-backend-2024/assets/14058396/dba62408-1c8c-43ca-bbbf-bf71723dd8f0)

**Comment by feralc** [comment]
@viniciusfcf  Acho que você está levando muito a sério rsrs Just have fun man! 
Eu não disse que a regra não está clara, eu disse que não deram ênfase nisso, e concorda que não faria muito sentido no mesmo texto dizerem que seria permitido até mesmo implementar um load balancer, se fosse pra ele ter um simples algoritmo de round robin? algo que qualquer load balancer de mercado já faz?

Quer ver um outro exemplo, nas regras também diz que deveriamos cadastrar os clientes iniciais, e que isso era imprescindível, a ideia de cadastro remete a ideia de inserção num banco de dados, certo?

![image](https://github.com/feralc/rinha-de-backend-2024/assets/12803319/85e38237-4af5-4ff2-b77e-34b936c6eb04)

Porém se você acompanhar lá no twitter o próprio @zanfranceschi disse que poderia ficar hardcoded, e muitas pessoas assim interpretaram tbm.

![image](https://github.com/feralc/rinha-de-backend-2024/assets/12803319/f8b57cdc-4d65-46d8-af46-d6581dc1eeb8)

Quer mais um exemplo:

Aqui diz que a arquitetura minima deveria ter esses "serviços", tratando o banco de dados como um serviço, muitas pessoas usaram SQLite, o que não sobe o banco de dados como um service.

![image](https://github.com/feralc/rinha-de-backend-2024/assets/12803319/a546563c-8d5d-464e-b5c8-da377f900f24)

Enfim, o que quero dizer com tudo isso é que no fim o que vale é o aprendizado e compartilhamento de conhecimento.

Se você comparar a maioria das soluções enviadas até agora fazem mais do mesmo mas com tecnologias diferentes, eu apenas queria usar uma abordagem diferente :) E acho que a minha solução nem é a mais performática!

E outra, os criteiros pra vencer são surpresa! Então ta safe, talvez eu passe bem longe, quanto a submissão vou manter, não vejo problema nisso!

**Comment by viniciusfcf** [comment]
@feralc cara, eu estou tranquilo, sério. Vou falar contigo como eu falaria com um amigo meu. Eu tou cagando pro resultado, eu mesmo entrei sabendo que não vou ganhar, nem entrei pra isso. Eu mesmo coloquei propriedades no banco que pra mim tiram um pouco da consistência que deveria ter, talvez no final eu até as adicione novamente.

Eu mandei essa issue pra você porque eu vi que você fez ip hashing e documentou, ou seja, não fez de má fé. Devo mandar issues para outros que possam estar fora dessas regras. Acho que você está certo, o SQLite não funciona como uma instância de service, mas na descrição da rinha não diz que o banco tem que ser acessado utilizando http. Se o Francisco vai aceitar ou não no ranking, é outra história, também.

**Comment by feralc** [comment]
É isso! Vamos aguardar!
